[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.138", features = ["derive"] }
smallvec = { version = "1.9.0", features = ["serde"] }
thiserror = "1.0.31"

[dev-dependencies]
bincode = "1.3.3"
