[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
[dependencies]
serde = { version = "1", features = ["derive"], optional=true}
smallvec = { version = "1", features = ["serde"] }
thiserror = "1"

[dev-dependencies]
bincode = "1.3.3"
