[package]
name = "cao-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["parallel", "serde"]
parallel=["rayon"]
[dependencies]
rayon = {version= "1.5.3", optional=true}
serde = { version = "1", features = ["derive"], optional=true}
thiserror = "1"

[dev-dependencies]
bincode = "1.3.3"
