[package]
name = "cecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["parallel", "serde", "tracing"]
parallel=["rayon"]

[dependencies]
parking_lot = "0.12.1"
rayon = {version= "1.5.3", optional=true}
serde = { version = "1", features = ["derive"], optional=true}
thiserror = "1"
tracing = { version = "0.1.35", optional = true , features=["release_max_level_warn"]}

[dev-dependencies]
bincode = "1.3.3"
